### ISSUE TITLE
As a briq user I want to import NFTs that I own on Ethereum and "briqify" them

### ISSUE THREAD

**Issue by s0lness** [briqNFT/briq-builder#24]
### User story 

As a user I want to have a briq version of my NFT

### Test
GIVEN I have connected my Metamask wallet to the app AND I have a compatible NFT
WHEN I choose a compatible NFT
THEN I get a briqified version of it on the builder I can mint

### References
https://github.com/Blackyugin/gotchibriqbuilder

**Comment by onlydust-contributor** [comment]
@MavericksFive is working on this issue
OnlyDust link : https://app.onlydust.xyz/contributions/0x0003
